export const ecommerceLinks = {
  ecommerceHome: "/",
  category: "/category",
  layoutcategory: "/category/:slug",
  EcommerceAboutPage: "/about",
  EcommerceShop: "/e-commerceshop",
  ProductDetail: "/e-commerceshop/:id",
  EcommerceContact: "/contact",
  EcomerceBlog: "/blogs",
  EcommerecSingleBlogPage: "/blog/:blogId",
  PrivacyPolicy: "/privacy",
  TermsAndConditions: "/terms",
  Shipping: "/shipping",
  Account: "/account",
  AccountOrder: "/account-orders",
  Cart: "/cart",
  Checkout: "/checkout",
};
